# This docker compose file is setup for local development only
services:
#   app:
#     build:
#       context: .
#       target: development
#     container_name: go-api-poc-app
#     volumes:
#       - .:/app
#     ports:
#       - "8080:8080"
#     depends_on:
#       db:
#         condition: service_healthy
#     environment:
#       VERSION: "1.0.0"
  
  db:
    image: mysql:8.0
    container_name: go-api-poc-db
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "5000:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 1s
      timeout: 2s
      # start_period: 10s
      retries: 10
