Description: Go POC ECS Service

Parameters:
  ProjectTag:
    Description: Tag to apply to resources in this stack
    Type: String
    Default: go-api-poc

Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${ProjectTag}-cluster
  
  ServiceTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${AWS::StackName}-tg # name cannot be longer than 32 characters
      HealthCheckIntervalSeconds: 6
      HealthCheckPath: /go/system/health
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      TargetType: ip
      Port: !ImportValue go-api-poc-ecs-task-container-port
      Protocol: HTTP
      UnhealthyThresholdCount: 10
      VpcId: !ImportValue go-api-poc-networking-VPCID
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 0

  Service:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub ${AWS::StackName}
      Cluster: !Ref Cluster
      DesiredCount: 1
      LaunchType: FARGATE
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true
      HealthCheckGracePeriodSeconds: 30
      LoadBalancers:
        - ContainerName: !ImportValue go-api-poc-ecs-task-container-name
          ContainerPort: !ImportValue go-api-poc-ecs-task-container-port
          TargetGroupArn: !Ref ServiceTargetGroup
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !ImportValue go-api-poc-alb-target-security-group
          Subnets:
            - !ImportValue go-api-poc-networking-PrivateSubnet1
            - !ImportValue go-api-poc-networking-PrivateSubnet2
            - !ImportValue go-api-poc-networking-PrivateSubnet3
      PropagateTags: SERVICE
      TaskDefinition: !ImportValue go-api-poc-ecs-task-task-definition-arn
      Tags:
        - Key: Project
          Value: !Ref ProjectTag
  
  LoadBalancerListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions: 
        - Type: forward
          Order: 1
          TargetGroupArn: !Ref ServiceTargetGroup
      Conditions: 
        - Field: path-pattern
          Values: 
            - "/go*"
      ListenerArn: !ImportValue go-api-poc-alb-listener-arn
      Priority: 1